### ISSUE TITLE
修改博客内容后，jekyll报错，无法将修改同步。需要重启jekyll服务才能完成内容同步。

### ISSUE THREAD

**Issue by reflectt6** [reflectt6/reflectt6.github.io#1]
报错内容如下：
E, [2024-01-30T17:27:52.853678 #7468] ERROR -- : Exception rescued in listen-worker_thread:
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
/Users/rainnight/.rubies/ruby-3.1.3/lib/ruby/3.1.0/pathname.rb:449:in `join'
/Users/rainnight/.rubies/ruby-3.1.3/lib/ruby/3.1.0/pathname.rb:449:in `block in children'
/Users/rainnight/.rubies/ruby-3.1.3/lib/ruby/3.1.0/pathname.rb:446:in `foreach'
/Users/rainnight/.rubies/ruby-3.1.3/lib/ruby/3.1.0/pathname.rb:446:in `children'

虽然可以通过重启实现内容同步，但是该说不说的，还是一定程度的影响开发效率。

**Comment by reflectt6** [comment]
通过观察报错信息，得到如下内容：
1、报错的核心在于字符集的不兼容
2、通过`ruby/3.1.0/pathname.rb`报错的路径，我们可以看到这应该是在读取文件的path过程中出错了
于是，合理猜测是由于路径中出现中文导致的。
